package com.ecommerce.model.enums;

public enum NotificationType {
    ORDER_CONFIRMATION,
    ORDER_SHIPPED,
    ORDER_DELIVERED,
    ORDER_CANCELLED,
    PAYMENT_SUCCESS,
    PAYMENT_FAILED,
    REFUND_PROCESSED,
    PROMOTIONAL,
    NEWSLETTER,
    ACCOUNT_WELCOME,
    PASSWORD_RESET,
    REVIEW_APPROVED,
    LOW_STOCK,
    SYSTEM_ALERT,
    SHIPPING_UPDATE
}
